"""API Registry: authoritative model and six #61 statuses (N014 / H63-N014).

Scope
-----
In-memory schema + registration rules only. Does **not** expose GET /v1/apis
(N016), persist projections (N015), or execute APIs (N017).

Authoritative states (issue #61)
--------------------------------
VERIFIED · PARTIAL · RESTRICTED · UNSUPPORTED · ERROR · DISABLED

Hard rule: ``GENERATED != VERIFIED``. Missing, false, or stale verification
metadata must never yield VERIFIED. An endpoint freshly generated by AI/adapter
is at best PARTIAL (or another non-VERIFIED state), never VERIFIED.

Invented ``verification_id`` + timestamp alone must never mint VERIFIED
(audit H63-N014): the id must be present in the process proof ledger issued
by an independent verify path (``issue_verification_proof``).

Deterministic identity
----------------------
Duplicate registrations with the same natural key
``(method, path, application_id, capability, source)`` produce the same
``id`` (``api_<sha256[:24]>``) and upsert in place. Status/verification fields
are re-validated on every register call.
"""
from __future__ import annotations

import hashlib
import threading
import time
from dataclasses import asdict, dataclass, replace
from enum import Enum
from typing import Any, Iterable, Mapping

API_REGISTRY_SCHEMA_VERSION = "1"

# How long a verification remains authoritative for VERIFIED without refresh.
# Stale last_verified_at demotes to PARTIAL (never silent VERIFIED).
DEFAULT_VERIFICATION_MAX_AGE_SEC = 7 * 24 * 3600


class ApiStatus(str, Enum):
    """Six authoritative API statuses from issue #61."""

    VERIFIED = "VERIFIED"
    PARTIAL = "PARTIAL"
    RESTRICTED = "RESTRICTED"
    UNSUPPORTED = "UNSUPPORTED"
    ERROR = "ERROR"
    DISABLED = "DISABLED"


class RegistrationRejected(ValueError):
    """Raised when a registration payload violates schema/status rules."""


def compute_api_id(
    *,
    method: str,
    path: str,
    application_id: str,
    capability: str,
    source: str,
) -> str:
    """Deterministic id from the natural key (duplicates → same id)."""
    method_n = (method or "").strip().upper()
    path_n = (path or "").strip()
    app_n = (application_id or "").strip()
    cap_n = (capability or "").strip()
    src_n = (source or "").strip().lower()
    raw = f"{method_n}\n{path_n}\n{app_n}\n{cap_n}\n{src_n}"
    digest = hashlib.sha256(raw.encode("utf-8")).hexdigest()[:24]
    return f"api_{digest}"


def _truthy_nonempty(value: Any) -> bool:
    if value is None:
        return False
    if isinstance(value, str):
        return bool(value.strip())
    return True


# ---------------------------------------------------------------------------
# Verification proof ledger (N014) — independent evidence, not client invention
# ---------------------------------------------------------------------------
_PROOF_LOCK = threading.RLock()
_ISSUED_VERIFICATION_IDS: set[str] = set()


def issue_verification_proof(verification_id: str | None = None) -> str:
    """Record (and optionally mint) a verification_id as independent proof.

    Only ids registered here may authorize ``ApiStatus.VERIFIED``. Callers that
    observe a real postcondition (api_test / adapter verify) must issue before
    writing VERIFIED into the registry.
    """
    import uuid

    vid = (verification_id or "").strip() or f"ver_{uuid.uuid4().hex}"
    with _PROOF_LOCK:
        _ISSUED_VERIFICATION_IDS.add(vid)
    return vid


def has_verification_proof(verification_id: Any) -> bool:
    if not _truthy_nonempty(verification_id):
        return False
    if verification_id is False or verification_id == 0:
        return False
    vid = str(verification_id).strip()
    with _PROOF_LOCK:
        return vid in _ISSUED_VERIFICATION_IDS


def clear_verification_proofs() -> None:
    """Test/teardown helper — drop all issued proofs."""
    with _PROOF_LOCK:
        _ISSUED_VERIFICATION_IDS.clear()


def _parse_epoch(value: Any) -> float | None:
    """Accept unix float/int or ISO-ish string with trailing Z; else None."""
    if value is None or value is False:
        return None
    if isinstance(value, (int, float)):
        if value <= 0:
            return None
        return float(value)
    if isinstance(value, str):
        s = value.strip()
        if not s:
            return None
        try:
            return float(s)
        except ValueError:
            pass
        # Minimal ISO-8601: YYYY-MM-DDTHH:MM:SS[.fff][Z|+00:00]
        try:
            from datetime import datetime, timezone

            if s.endswith("Z"):
                s = s[:-1] + "+00:00"
            dt = datetime.fromisoformat(s)
            if dt.tzinfo is None:
                dt = dt.replace(tzinfo=timezone.utc)
            return dt.timestamp()
        except ValueError:
            return None
    return None


def map_lifecycle_to_status(lifecycle: str | None) -> ApiStatus:
    """Map internal/adapter verification lifecycle labels → six #61 statuses.

    Unknown / generated / discovered labels are **never** VERIFIED.
    """
    if lifecycle is None:
        return ApiStatus.PARTIAL
    key = str(lifecycle).strip().upper()
    if not key:
        return ApiStatus.PARTIAL

    # Already one of the six
    try:
        return ApiStatus(key)
    except ValueError:
        pass

    mapping = {
        "GENERATED": ApiStatus.PARTIAL,
        "UNKNOWN": ApiStatus.PARTIAL,
        "DISCOVERED": ApiStatus.PARTIAL,
        "PASS": ApiStatus.VERIFIED,  # candidate only; register() still gates
        "FAILED": ApiStatus.ERROR,
        "FAIL": ApiStatus.ERROR,
        "BLOCKED": ApiStatus.RESTRICTED,
        "UNSTABLE": ApiStatus.PARTIAL,
        "DENIED": ApiStatus.RESTRICTED,
        "REVOKED": ApiStatus.DISABLED,
        "OFF": ApiStatus.DISABLED,
        "INACTIVE": ApiStatus.DISABLED,
    }
    return mapping.get(key, ApiStatus.PARTIAL)


def map_d3_envelope_to_status(envelope: Mapping[str, Any] | None) -> ApiStatus:
    """Map a D3-style capability envelope to an authoritative API status.

    D3 envelopes use ``supported`` / ``error_code`` (see ``os.capability``).
    A successful supported envelope is PARTIAL here — not VERIFIED — because
    discovery ≠ effect verification (GENERATED != VERIFIED).
    """
    if not envelope or not isinstance(envelope, Mapping):
        return ApiStatus.ERROR

    supported = envelope.get("supported")
    error_code = str(envelope.get("error_code") or "").strip().upper()

    if supported is False:
        if error_code in {"CAPABILITY_NOT_SUPPORTED"}:
            return ApiStatus.UNSUPPORTED
        if error_code in {"CAPABILITY_UNAVAILABLE"}:
            return ApiStatus.ERROR
        if error_code in {"DISCOVERY_FAILED"}:
            return ApiStatus.ERROR
        return ApiStatus.UNSUPPORTED

    if error_code == "DISCOVERY_FAILED":
        return ApiStatus.ERROR

    if supported is True:
        # Honest discovery is not effect verification.
        return ApiStatus.PARTIAL

    # Ambiguous / missing supported → not success.
    return ApiStatus.ERROR


@dataclass(frozen=True)
class ApiRecord:
    """One registry entry matching the #61 schema (plus schema_version)."""

    id: str
    name: str
    method: str
    path: str
    description: str
    source: str
    application_id: str
    adapter_id: str
    capability: str
    status: ApiStatus
    permissions: tuple[str, ...]
    authentication_required: bool
    created_at: float
    updated_at: float
    last_verified_at: float | None
    verification_id: str | None
    schema_version: str = API_REGISTRY_SCHEMA_VERSION

    def to_dict(self) -> dict[str, Any]:
        d = asdict(self)
        d["status"] = self.status.value
        d["permissions"] = list(self.permissions)
        return d


def _coerce_status(raw: Any) -> ApiStatus:
    if isinstance(raw, ApiStatus):
        return raw
    if raw is None:
        raise RegistrationRejected("status is required")
    try:
        return ApiStatus(str(raw).strip().upper())
    except ValueError as exc:
        raise RegistrationRejected(
            f"status must be one of {[s.value for s in ApiStatus]}, got {raw!r}"
        ) from exc


def authorize_verified_status(
    *,
    status: ApiStatus,
    verification_id: Any,
    last_verified_at: Any,
    now: float | None = None,
    max_age_sec: float = DEFAULT_VERIFICATION_MAX_AGE_SEC,
) -> ApiStatus:
    """Return a status that is allowed given verification metadata.

    If the caller asks for VERIFIED but evidence is missing/false/stale,
    demote to PARTIAL (never raise solely for demotion — registration should
    remain possible with an honest status).
    """
    if status is not ApiStatus.VERIFIED:
        return status

    vid_ok = _truthy_nonempty(verification_id)
    # Explicit false / 0 / empty are false metadata
    if verification_id is False or verification_id == 0:
        vid_ok = False

    ts = _parse_epoch(last_verified_at)
    if last_verified_at is False:
        ts = None

    if not vid_ok or ts is None:
        return ApiStatus.PARTIAL

    # Invented id+timestamp is not independent proof (audit H63-N014).
    if not has_verification_proof(verification_id):
        return ApiStatus.PARTIAL

    clock = time.time() if now is None else now
    age = clock - ts
    if age < 0:
        # Future timestamp → treat as false/untrusted metadata
        return ApiStatus.PARTIAL
    if age > max_age_sec:
        return ApiStatus.PARTIAL
    return ApiStatus.VERIFIED


class ApiRegistry:
    """Thread-safe in-memory API registry (N014). Persistence → N015."""

    def __init__(self, *, verification_max_age_sec: float = DEFAULT_VERIFICATION_MAX_AGE_SEC):
        self._lock = threading.RLock()
        self._by_id: dict[str, ApiRecord] = {}
        self._verification_max_age_sec = verification_max_age_sec

    def clear(self) -> None:
        with self._lock:
            self._by_id.clear()

    def list(self) -> list[ApiRecord]:
        with self._lock:
            return sorted(self._by_id.values(), key=lambda r: r.id)

    def get(self, api_id: str) -> ApiRecord | None:
        with self._lock:
            return self._by_id.get(api_id)

    def register(
        self,
        payload: Mapping[str, Any],
        *,
        now: float | None = None,
        force_id: str | None = None,
    ) -> ApiRecord:
        """Register or upsert an API record.

        Rules
        -----
        * Natural key → deterministic ``id`` (unless ``force_id`` / payload ``id``
          matches an existing record's key — ``id`` in payload is ignored when
          it disagrees with the computed id; the computed id always wins so
          duplicates stay deterministic).
        * ``schema_version`` always set to ``API_REGISTRY_SCHEMA_VERSION``.
        * Requested VERIFIED without valid ``verification_id`` + fresh
          ``last_verified_at`` is demoted to PARTIAL.
        * Lifecycle labels like GENERATED/DISCOVERED never become VERIFIED
          unless evidence passes ``authorize_verified_status``.
        """
        clock = time.time() if now is None else now

        method = str(payload.get("method") or "").strip().upper()
        path = str(payload.get("path") or "").strip()
        application_id = str(payload.get("application_id") or "").strip()
        capability = str(payload.get("capability") or "").strip()
        source = str(payload.get("source") or "").strip()
        name = str(payload.get("name") or "").strip()

        if not method or not path or not name or not source or not capability:
            raise RegistrationRejected(
                "name, method, path, source, and capability are required"
            )

        api_id = compute_api_id(
            method=method,
            path=path,
            application_id=application_id,
            capability=capability,
            source=source,
        )
        if force_id is not None:
            # Tests / migration hooks only — still must be non-empty.
            if not str(force_id).strip():
                raise RegistrationRejected("force_id must be non-empty")
            api_id = str(force_id).strip()

        raw_status = payload.get("status")
        # GENERATED / DISCOVERED / UNKNOWN are not members of the six states;
        # treat them as honest non-VERIFIED (PARTIAL) before enum coercion.
        if isinstance(raw_status, str) and raw_status.strip().upper() in {
            "GENERATED",
            "UNKNOWN",
            "DISCOVERED",
        }:
            status = ApiStatus.PARTIAL
        elif raw_status is None and payload.get("lifecycle") is not None:
            status = map_lifecycle_to_status(payload.get("lifecycle"))
        elif raw_status is None and isinstance(payload.get("d3"), Mapping):
            status = map_d3_envelope_to_status(payload["d3"])
        elif raw_status is None:
            # Fresh registration without status ≡ generated → PARTIAL
            status = ApiStatus.PARTIAL
        else:
            status = _coerce_status(raw_status)

        verification_id = payload.get("verification_id")
        last_verified_at_raw = payload.get("last_verified_at")
        status = authorize_verified_status(
            status=status,
            verification_id=verification_id,
            last_verified_at=last_verified_at_raw,
            now=clock,
            max_age_sec=self._verification_max_age_sec,
        )

        last_verified_at = _parse_epoch(last_verified_at_raw)
        if status is not ApiStatus.VERIFIED:
            # Do not advertise verification fields as if authoritative when
            # status is not VERIFIED — keep ids for audit but timestamps that
            # failed the gate stay as parsed (may be None).
            if not _truthy_nonempty(verification_id) or verification_id is False:
                verification_id = None
            if last_verified_at_raw is False:
                last_verified_at = None

        perms_raw = payload.get("permissions") or []
        if not isinstance(perms_raw, Iterable) or isinstance(perms_raw, (str, bytes)):
            raise RegistrationRejected("permissions must be a list of strings")
        permissions = tuple(str(p) for p in perms_raw)

        auth_req = bool(payload.get("authentication_required", True))
        description = str(payload.get("description") or "")
        adapter_id = str(payload.get("adapter_id") or "")

        with self._lock:
            existing = self._by_id.get(api_id)
            created_at = existing.created_at if existing is not None else clock
            # Prefer payload created_at only on first insert
            if existing is None and payload.get("created_at") is not None:
                parsed_created = _parse_epoch(payload.get("created_at"))
                if parsed_created is not None:
                    created_at = parsed_created

            record = ApiRecord(
                id=api_id,
                name=name,
                method=method,
                path=path,
                description=description,
                source=source,
                application_id=application_id,
                adapter_id=adapter_id,
                capability=capability,
                status=status,
                permissions=permissions,
                authentication_required=auth_req,
                created_at=created_at,
                updated_at=clock,
                last_verified_at=last_verified_at,

                verification_id=(
                    str(verification_id).strip()
                    if _truthy_nonempty(verification_id) and verification_id is not False
                    else None
                ),
                schema_version=API_REGISTRY_SCHEMA_VERSION,
            )
            # If VERIFIED, both evidence fields must be present on the record
            if record.status is ApiStatus.VERIFIED and (
                not record.verification_id or record.last_verified_at is None
            ):
                record = replace(record, status=ApiStatus.PARTIAL)

            self._by_id[api_id] = record
            return record

    def set_status(self, api_id: str, status: ApiStatus | str) -> ApiRecord:
        """Update status with the same VERIFIED evidence gate."""
        st = _coerce_status(status)
        with self._lock:
            existing = self._by_id.get(api_id)
            if existing is None:
                raise KeyError(api_id)
            st = authorize_verified_status(
                status=st,
                verification_id=existing.verification_id,
                last_verified_at=existing.last_verified_at,
                max_age_sec=self._verification_max_age_sec,
            )
            updated = replace(existing, status=st, updated_at=time.time())
            self._by_id[api_id] = updated
            return updated


_REGISTRY: ApiRegistry | None = None
_REGISTRY_LOCK = threading.Lock()


def get_api_registry() -> ApiRegistry:
    global _REGISTRY
    with _REGISTRY_LOCK:
        if _REGISTRY is None:
            _REGISTRY = ApiRegistry()
        return _REGISTRY


def reset_api_registry() -> ApiRegistry:
    """Replace the process singleton (tests) and drop proof ledger."""
    clear_verification_proofs()
    global _REGISTRY
    with _REGISTRY_LOCK:
        _REGISTRY = ApiRegistry()
        return _REGISTRY
