"""Abstract OS backend protocol."""
from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class OSBackend(Protocol):
    name: str

    # System
    def get_system_info(self) -> dict[str, Any]: ...
    def get_resources(self) -> dict[str, Any]: ...
    def get_uptime(self) -> dict[str, Any]: ...
    def power_action(self, action: str) -> dict[str, Any]: ...

    # Processes
    def list_processes(self) -> list[dict[str, Any]]: ...
    def get_process(self, pid: int) -> dict[str, Any] | None: ...
    def start_process(self, command: str, args: list[str] | None = None) -> dict[str, Any]: ...
    def terminate_process(self, pid: int) -> dict[str, Any]: ...

    # Apps
    def discover_apps(self) -> list[dict[str, Any]]: ...

    # Windows
    def list_windows(self) -> list[dict[str, Any]]: ...
    def get_window(self, hwnd: int) -> dict[str, Any] | None: ...
    def focus_window(self, hwnd: int) -> dict[str, Any]: ...
    def close_window(self, hwnd: int) -> dict[str, Any]: ...

    # UI tree
    def get_ui_tree(self, hwnd: int | None = None) -> dict[str, Any]: ...

    # Input
    def mouse_move(self, x: int, y: int) -> dict[str, Any]: ...
    def mouse_click(self, x: int, y: int, button: str = "left") -> dict[str, Any]: ...
    def key_press(self, key: str, modifiers: list[str] | None = None) -> dict[str, Any]: ...
    def type_text(self, text: str) -> dict[str, Any]: ...

    # Clipboard
    def clipboard_get(self) -> dict[str, Any]: ...
    def clipboard_set(self, text: str) -> dict[str, Any]: ...

    # Display
    def list_displays(self) -> list[dict[str, Any]]: ...
    def screenshot(self, display_id: int | None = None) -> dict[str, Any]: ...

    # Filesystem
    def fs_list(self, path: str) -> list[dict[str, Any]]: ...
    def fs_read(self, path: str, max_bytes: int = 65536) -> dict[str, Any]: ...
    def fs_write(self, path: str, content: str) -> dict[str, Any]: ...
    def fs_delete(self, path: str) -> dict[str, Any]: ...

    # Storage
    def list_drives(self) -> list[dict[str, Any]]: ...

    # Network
    def network_interfaces(self) -> list[dict[str, Any]]: ...
    def network_connections(self) -> list[dict[str, Any]]: ...

    # Services
    def list_services(self) -> list[dict[str, Any]]: ...
    def control_service(self, name: str, action: str) -> dict[str, Any]: ...

    # Audio
    def audio_devices(self) -> list[dict[str, Any]]: ...
    def audio_volume(self) -> dict[str, Any]: ...

    # Devices
    def list_devices(self) -> list[dict[str, Any]]: ...

    # Printers
    def list_printers(self) -> list[dict[str, Any]]: ...

    # Users / sessions
    def list_users(self) -> list[dict[str, Any]]: ...
    def list_sessions(self) -> list[dict[str, Any]]: ...

    # Registry
    def registry_read(self, path: str, name: str | None = None) -> dict[str, Any]: ...
    def registry_write(self, path: str, name: str, value: Any) -> dict[str, Any]: ...

    # Terminal
    def terminal_execute(
        self, command: str, policy: str = "ALLOW"
    ) -> dict[str, Any]: ...
